version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: javaSpringLR
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"

  app:
    image: eclipse-temurin:11-jre-jammy
    container_name: springboot_app
    volumes:
      - ./target/JavaSpringLR5-1.0.0-SNAPSHOT.jar:/app/app.jar
    command: java -jar /app/app.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
